### PR TITLE
Updated docs for Windows development

### PR DESCRIPTION
**Pull request by souvik362**
## Type of Change

- **Other:** Updated docs for Windows development

## What issue does this relate to?

N/A

### What should this PR do?

Add notes to docs about working with the website in a Windows environment.

### What are the acceptance criteria?

Docs changes make sense.

### CODE REVIEW

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
`morgan` is a runtime dependency in `server/app.js`, moving `morgan` to devDeps results in it not being present at runtime when deployed to Heroku

**Comment by souvik362** [comment]
## Changes made
* Moved `morgan` back to dependencies
* Added a tricks for developing in windows (more details provided below)

#### why i added a development in windows para

I personally develop in vs-code  in windows so the `npm run dev`  script doesn't work fork me and giving me this error
envError
 I find out why this error is happening in this [stackoverflow thread ](https://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman) and also the answer.

this will be really helpful for them who develop in windows .
@MattIPv4 what you think about this change Let me know

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
As this is now just a docs change, please revert the changes to package-lock.json

**Comment by souvik362** [comment]
Thanks for reviewing @MattIPv4 .
I added changes as you suggested in package-lock.json.
I will add PWA Support in this app for faster performance Later.

**Review by MattIPv4 — APPROVED** [review]
Lgtm

**Pull request merged**
