### PR TITLE
Some layput changes in about page

### PR DESCRIPTION
**Pull request by souvik362**
- **Layouts:** 

Make Layout changes to about page

### Before
Web capture_1-12-2020_175033_cdnjs com

### After
Web capture_1-12-2020_174940_localhost

### Before
Web capture_1-12-2020_174012_cdnjs com

### After
Web capture_1-12-2020_173947_localhost

### CODE REVIEW

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
👋 I appreciate the changes to the mobile view, but am not keen on the desktop layout view.

The sponsor panels are designed to be in a 2 wide grid layout, not a 3 wide layout. If you feel that content needs to be wrapped, please `Countribute` & `Legal` below `Who are we?` instead.

Please also resolve all the CI failures.

**Comment by souvik362** [comment]
Hey @MattIPv4 ,
thanks for reviewing the PR.
But for now i would love to close this PR because i am happy with changes you made on #64  and #63 
those are awesome. 

### Suggestion 

1. I think Tooling for this app is very heavy and nuxt takes some time to re-compile and hot-reload the app. please try to make the tooling small and hot reload fast. (use NEXTJS )
2.Minify the severed pages
3. try to statically prerender page that not change much ( about / api)

### All the suggestions  i mentioned can be achieved with nextjs with ease and this will the made the site fast and much more seo friendly.

**Comment by MattIPv4** [comment]
> I think Tooling for this app is very heavy and nuxt takes some time to re-compile and hot-reload the app. please try to make the tooling small and hot reload fast. (use NEXTJS )

I'm not going to move the entire project to a different framework (Vue -> React) just because building the app in development is a bit slow, sorry.

> Minify the severed pages

All responses are minified in production 👍 

> try to statically prerender page that not change much ( about / API)

No page can be statically rendered, they all have components that rely on talking to the API, which is why this uses SSR.

> All the suggestions i mentioned can be achieved with nextjs with ease and this will the make the site fast and much more seo friendly.

No, changing from Vue to React, and Nuxt to Next, will not automatically bring a faster experience and better SEO. That's not how that works. I'm not overly sure where your great concern about site speed comes from, production loads in ~200ms. The site is also well optimised for SEO and has a good ranking in Google's web console.

**Comment by souvik362** [comment]
@MattIPv4 
### I completely agree with all the points you have mentioned.

I found some issues on lighthouse test that I will create a issue later. Please check it out

I mostly develop sites in react and next so i know about them better than Vue.
So it's just an opinion

**Pull request closed without merging**
